language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andrew2892/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrew2892/react-test npm test

after_success:
  - docker build -t andrew2892/client ./client
  - docker build -t andrew2892/nginx ./nginx
  - docker build -t andrew2892/server ./server
  - docker build -t andrew2892/worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image 
  - docker push andrew2892/client
  - docker push andrew2892/nginx
  - docker push andrew2892/server
  - docker push andrew2892/worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-956681145389"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY