version: "3"
services: 
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  postgres: 
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /home/node/app/node_modules
      - ./server:/home/node/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /home/node/app/node_modules
      - ./worker:/home/node/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    